name: check lint
on:
  push:
    branches:
      - master
jobs:
  check_lint_job: 
  runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2 # this checkouts out the code of the repo 
      - uses: actions/setup-node@v1  
         with:
           node-version: 12.x  
      - name: install dependencies
        run: npm install
      - name: lint
        run: npm run eslint
